### ISSUE TITLE
Data export from Spine 3.8.xx 

### ISSUE THREAD

**Issue by valukard** [playcanvas/playcanvas-spine#26]
Hello,

I use spine 3.8.xx version.. When I export data from spine to playcanvas it's not working because of version. In contrib/spine-ts there is a warning: Spine-ts works with data exported from Spine 3.6.xx.
What can I do to upgrade to 3.8.xx version(how can I create a compatible playcanvas-spine.js) or do you have a plan to create a new playcanvas-spine.min.js for 3.8.xx?

Thank you

**Comment by willeastcott** [comment]
Hi @valukard! As a little weekend project, I started looking into this. So I've done a few things:

1. I've updated the build system to generate both minified and unminified builds of the playcanvas-spine library in both 3.6 and 3.8 flavors.
2. I've updated the 'engine-only' examples to be much cleaner and simpler.

I tried loading a 3.8 exported character (the hero) into the 3.8 lib but it throws an exception. I suspect the spine-ts API has changed a bit between 3.6 and 3.8. I've kind of run out of time to continue for this weekend unfortunately. If you or anyone else wants to investigate, that'd be great! Otherwise, hopefully I'll be able to revisit this as time allows.

**Comment by willeastcott** [comment]
Actually, I just made [this commit](https://github.com/playcanvas/playcanvas-spine/commit/ca46a0e52d90748f35e9cd4b34eed62f6c31f489) which seems to make the playcanvas-spine.3.8.js lib work with Spine Essential 3.8 exports. Exports from the Pro version that contain PathAttachments aren't (yet) supported in this lib.

**Comment by valukard** [comment]
Hi Will..
Thanks for your helps. Exports from spine 3.8 works properly
Best regards
