### ISSUE TITLE
Runtime Error in Internet Explorer 11

### ISSUE THREAD

**Issue by dexterdeluxe88** [playcanvas/playcanvas-spine#5]
Launch 
https://launch.playcanvas.com/581347 
in Internet Explorer 11

Observe
Error: Object doesn't support property or method 'map'
File: playcanvas-spine.min.js, Line: 3, Column: 17925

Notes
This is a minimal example project with the most current version of the playcanvas-spine library, which works in Chrome and Edge. But i think the issue is that IE 11 has a different implementation of Float32Array and uses a object type instead of a float type.

**Comment by willeastcott** [comment]
This exception originates from this line:

https://github.com/playcanvas/playcanvas-spine/blob/master/src/plugin/spine.js#L195

This is happening because the object calling map is not an Array (IE11 supports Array.prototype.map). It's a Float32Array. Other browsers let you get away with this. But it seems that IE11 doesn't.

**Comment by willeastcott** [comment]
I've attempted a [fix](https://github.com/playcanvas/playcanvas-spine/pull/6). I'll let @daredevildave review it.
